// Audio cue player. Client-only (references Audio + localStorage). Every cue
// is optional — if no file for that cue exists, the call is a silent no-op.
//
// For each cue we look for the file at /sounds/{cue}.mp3 FIRST, then fall
// back to /sounds/{cue}.wav. This lets the user drop an .mp3 downloaded
// from Pixabay/Mixkit straight in without having to first delete the
// placeholder .wav generated by scripts/gen-sounds.mjs — the .mp3 wins.
// Resolution happens lazily on the first playCue for that cue via a HEAD
// probe, then cached; the very first play may be silent while the probe
// runs, subsequent plays hit the resolved element immediately.

const CUE_KEYS = [
  'deal',
  'fold',
  'check',
  'call',
  'raise',
  'allin',
  'street',
  'win',
  'myturn',
] as const;

export type SoundCue = (typeof CUE_KEYS)[number];

const MUTED_KEY = 'holdem:sound-muted';
// undefined key = never attempted; entry present but null = probed and no
// file found (both extensions 404); entry present with Audio = ready to play.
const audioPool = new Map<SoundCue, HTMLAudioElement | null>();
const resolvePending = new Set<SoundCue>();

export function isMuted(): boolean {
  if (typeof window === 'undefined') return true;
  return window.localStorage.getItem(MUTED_KEY) === '1';
}

export function setMuted(muted: boolean): void {
  if (typeof window === 'undefined') return;
  if (muted) window.localStorage.setItem(MUTED_KEY, '1');
  else window.localStorage.removeItem(MUTED_KEY);
}

async function resolveAudio(cue: SoundCue): Promise<HTMLAudioElement | null> {
  for (const ext of ['mp3', 'wav'] as const) {
    const url = `/sounds/${cue}.${ext}`;
    try {
      const res = await fetch(url, { method: 'HEAD' });
      if (res.ok) {
        const audio = new Audio(url);
        audio.preload = 'auto';
        return audio;
      }
    } catch {
      // Network error — try the next extension.
    }
  }
  return null;
}

export function playCue(cue: SoundCue): void {
  if (typeof window === 'undefined') return;
  if (isMuted()) return;

  const cached = audioPool.get(cue);
  if (cached === null) return; // probed, nothing there — permanent silence
  if (cached) {
    try {
      cached.currentTime = 0;
      void cached.play().catch(() => {
        // Autoplay policy or codec issue — silent no-op is fine.
      });
    } catch {
      // Some browsers throw setting currentTime before metadata loads.
    }
    return;
  }

  // Not yet resolved. Kick off the probe (deduped) and skip this play —
  // next call for the same cue will hit the cached element. In practice
  // the eager probe below runs at module load, so this branch only
  // matters if playCue fires during that ~9-HEAD-request window.
  if (resolvePending.has(cue)) return;
  resolvePending.add(cue);
  void resolveAudio(cue).then((audio) => {
    audioPool.set(cue, audio);
    resolvePending.delete(cue);
  });
}

// Eager background probe so the very first playCue for each cue lands on
// a resolved element instead of missing while HEAD requests fly. Guarded
// against SSR since `fetch` + `Audio` aren't available server-side.
if (typeof window !== 'undefined') {
  for (const cue of CUE_KEYS) {
    resolvePending.add(cue);
    void resolveAudio(cue).then((audio) => {
      audioPool.set(cue, audio);
      resolvePending.delete(cue);
    });
  }
}

